"""empty message

Revision ID: 7d17d468f452
Revises: 577039c46fbe
Create Date: 2021-07-23 15:18:53.910198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d17d468f452'
down_revision = '577039c46fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('featured', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'featured')
    # ### end Alembic commands ###
