"""empty message

Revision ID: b37c31c05b9b
Revises: 7d17d468f452
Create Date: 2021-07-25 18:46:32.484625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b37c31c05b9b'
down_revision = '7d17d468f452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('subject_title', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'subject_title')
    # ### end Alembic commands ###
