"""empty message

Revision ID: c039afcf2bc1
Revises: be8f372bc72a
Create Date: 2021-08-06 19:35:40.151190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c039afcf2bc1'
down_revision = 'be8f372bc72a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('time_limit1', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('time_limit2', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'time_limit2')
    op.drop_column('post', 'time_limit1')
    # ### end Alembic commands ###
